### ISSUE TITLE
Defining multiple ranges

### ISSUE THREAD

**Issue by forresto** [francisrstokes/super-expressive#81] opened 2024-08-08 11:35 UTC
``` js
    const ranges = [["a", "z"], ["A", "Z"]];
    const seRanges = SuperExpressive().anyOf;
    for (const range of ranges) {
      const [rangeStart, rangeEnd] = range;
      seRanges.range(rangeStart, rangeEnd);
    }
    seRanges.end();
```

Expected 

``` js
/[a-zA-Z]/
```

Actual 

> Cannot compute the value of a not yet fully specified regex object. (Try adding a .end() call to match the "anyOf")

Is there another way to programmatically build up ranges?

**Comment by francisrstokes** [comment] 2024-08-08 11:40
Can you try:

```javascript
    const ranges = [["a", "z"], ["A", "Z"]];
    let seRanges = SuperExpressive().anyOf;
    for (const range of ranges) {
      const [rangeStart, rangeEnd] = range;
      seRanges  = seRanges.range(rangeStart, rangeEnd);
    }
    seRanges = seRanges.end();
```

**Comment by francisrstokes** [comment] 2024-08-08 14:19
Explanation is `SuperExpressive` objects are not mutable (by design), so you need to re-assign to the object you're building.

**Closed as completed by francisrstokes** 2024-08-08 14:19 UTC
